//
//  NSManagedObject.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - NSManagedObject properties

extension NSManagedObject {

    @NSManaged var id: String?
    @NSManaged var path: String?
    @NSManaged var state: Int32 // cannot mark as optional because Objective-C compatibility issues

    @NSManaged var syncedFiles: SyncthingFolder?

}

// MARK: - NSManagedObject query attributes

extension NSManagedObject {

    static let id = AlecrimCoreData.NullableAttribute<String>("id")
    static let path = AlecrimCoreData.NullableAttribute<String>("path")
    static let state = AlecrimCoreData.NullableAttribute<Int32>("state")

    static let syncedFiles = AlecrimCoreData.NullableAttribute<SyncthingFolder>("syncedFiles")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: NSManagedObject {

    var id: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("id", self) }
    var path: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("path", self) }
    var state: AlecrimCoreData.NullableAttribute<Int32> { return AlecrimCoreData.NullableAttribute<Int32>("state", self) }

    var syncedFiles: AlecrimCoreData.NullableAttribute<SyncthingFolder> { return AlecrimCoreData.NullableAttribute<SyncthingFolder>("syncedFiles", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var syncthingFolders: AlecrimCoreData.Table<NSManagedObject> { return AlecrimCoreData.Table<NSManagedObject>(dataContext: self) }

}

